### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by csprocket777** [cisco-ce/jsxapi#89]
Trying to use this as an ES6 import like this:
```javascript
import * as XAPI from 'jsxapi';
```

And when I go to use it:
```javascript
    let jsxapi = XAPI;
    this.deviceConnection = jsxapi.connect(`wss://${this.deviceIP}`, {
      username: this.deviceAdminUsername,
      password: this.deviceAdminPassword
    })
    .on('error', console.error)
    .on('ready', async (xapi:any)=>{
      console.log("WE'VE CONNECTED!")
      xapi.close();
    })
```

I get the following error:
```
Uncaught ReferenceError: Buffer is not defined
    at generateAuthSubProto (ws.js:1:493)
    at websocketConnect (ws.js:1:922)
    at initBackend (browser.js:1:1069)
    at Object.eval [as connect] (connect.js:1:1861)
    at Index.connectToDevice (index.js:47:1)
    at EmberCuiButton.clickHandler (ember-cui-button.js:185:1)
```

Any suggestions?

**Comment by csprocket777** [comment]
For anyone else running into this issue with hopes of simply using the import system, I found I had to include the script in the main `index.html` page as instructed here: https://roomos.cisco.com/docs/JSXAPI/Browser.md
